version: "3.4"
services:
  db:
    image: mysql:5.6
    container_name: 'db.${ENDPOINT_NAME}'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: smena
      MYSQL_PASSWORD: smena
      MYSQL_DATABASE: smena
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - ./db/data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
      - ./data/dump:/docker-entrypoint-initdb.d
  web:
    image: nginx:latest
    restart: unless-stopped
    container_name: 'web.${ENDPOINT_NAME}'
    ports:
      - "8005:80"
    environment:
      ENDPOINT_NAME: ${ENDPOINT_NAME}
    command: sh -c "envsubst '$$ENDPOINT_NAME' < /etc/nginx/conf.d/site.template > /etc/nginx/conf.d/site.conf && exec nginx -g 'daemon off;'"
    volumes:
      - ./nginx/config:/etc/nginx/conf.d
      - ./data/logs/nginx:/var/log/nginx
      - /etc/localtime:/etc/localtime:ro
      - ../:/var/www/html
  php:
    build:
      context: ./php
    container_name: 'php.${ENDPOINT_NAME}'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ../:/var/www/html
